import Database from 'better-sqlite3';import fs from 'fs';import path from 'path';import type {GameEvent,GameState} from '@/domain/types';import {initialState,replay} from '@/domain/types';
let db:Database.Database|undefined;
export function database(){if(db)return db;const file=process.env.DATABASE_PATH||'./data/pet-society.db';fs.mkdirSync(path.dirname(file),{recursive:true});db=new Database(file);db.pragma('journal_mode = WAL');db.exec(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,created_at INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS login_codes(email TEXT PRIMARY KEY,code_hash TEXT NOT NULL,expires_at INTEGER NOT NULL,attempts INTEGER NOT NULL DEFAULT 0);CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY AUTOINCREMENT,aggregate_id TEXT NOT NULL,event_type TEXT NOT NULL,event_data TEXT NOT NULL,timestamp INTEGER NOT NULL,version INTEGER NOT NULL,UNIQUE(aggregate_id,version));CREATE INDEX IF NOT EXISTS idx_events_aggregate ON events(aggregate_id,version);`);return db;}
export function userByEmail(email:string){return database().prepare('SELECT * FROM users WHERE email=?').get(email) as {id:string,email:string}|undefined;}
export function userById(id:string){return database().prepare('SELECT * FROM users WHERE id=?').get(id) as {id:string,email:string}|undefined;}
export function createUser(email:string){const id=crypto.randomUUID();database().prepare('INSERT INTO users(id,email,created_at) VALUES(?,?,?)').run(id,email,Date.now());return{id,email};}
export function eventsFor(id:string){return database().prepare('SELECT * FROM events WHERE aggregate_id=? ORDER BY version').all(id) as GameEvent[];}
export function stateFor(id:string):GameState|null{const u=userById(id);return u?replay(initialState(u.id,u.email),eventsFor(id)):null;}
export function append(id:string,type:string,data:unknown){const d=database();const tx=d.transaction(()=>{const row=d.prepare('SELECT COALESCE(MAX(version),0) version FROM events WHERE aggregate_id=?').get(id) as {version:number};d.prepare('INSERT INTO events(aggregate_id,event_type,event_data,timestamp,version) VALUES(?,?,?,?,?)').run(id,type,JSON.stringify(data),Date.now(),row.version+1);});tx();return stateFor(id)!;}
