import {NextResponse} from 'next/server';import {z} from 'zod';import {sessionUser} from '@/lib/auth';import {append,stateFor} from '@/lib/db';import {ITEMS} from '@/domain/types';
const schema=z.object({type:z.string(),payload:z.record(z.string(),z.unknown()).default({})});
export async function POST(req:Request){const id=await sessionUser();if(!id)return NextResponse.json({error:'Unauthorized'},{status:401});const parsed=schema.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:'Invalid command'},{status:400});const {type,payload:p}=parsed.data;const s=stateFor(id)!;try{let event='';let data:Record<string,unknown>={};switch(type){
 case'design':{const d=z.object({name:z.string().trim().min(2).max(18),species:z.enum(['cat','dog','bunny','bear']),body:z.string(),ears:z.string(),eyes:z.string(),muzzle:z.string(),pattern:z.string(),patternColor:z.string(),accessory:z.string()}).parse(p);event='PetDesigned';data=d;break;}
 case'care':{const d=z.object({need:z.enum(['hunger','hygiene','happiness','energy'])}).parse(p);event='CarePerformed';data={need:d.need,amount:18,coins:8,xp:6};break;}
 case'buy':{const d=z.object({itemId:z.string()}).parse(p);const item=ITEMS.find(i=>i.id===d.itemId);if(!item)throw Error('Item not found');if(item.level>s.level)throw Error(`Unlocks at level ${item.level}`);if(s.coins<item.price)throw Error('Not enough coins');event='ItemPurchased';data={itemId:item.id,price:item.price};break;}
 case'use':{const d=z.object({itemId:z.string()}).parse(p);if(!s.inventory[d.itemId])throw Error('You do not own that');const item=ITEMS.find(i=>i.id===d.itemId);event='ItemUsed';data={itemId:d.itemId,...(item?.category==='food'?{need:'hunger',amount:25}:{})};break;}
 case'equip':event='ItemEquipped';data={items:z.array(z.string()).max(4).parse(p.items)};break;
 case'decorate':event='RoomDecorated';data={items:z.array(z.string()).max(12).parse(p.items)};break;
 case'daily':{const day=new Date().toISOString().slice(0,10);if(s.lastDaily===day)throw Error('Already claimed today');const yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);const streak=s.lastDaily===yesterday?Math.min(5,s.streak+1):1;event='DailyClaimed';data={day,streak,coins:75*streak,gems:streak===5?2:0};break;}
 case'play':{const d=z.object({game:z.enum(['fishing','treasure','racing','cooking'])}).parse(p);const rewards={fishing:['Bubblefish','Moon Koi','Buttonfish'],treasure:['Moon Coin','Tiny Fossil','Crystal Acorn'],racing:['Ribbon'],cooking:['Pancakes']} as const;const reward=rewards[d.game][Math.floor(Math.random()*rewards[d.game].length)];const won=d.game!=='racing'||Math.random()>.35;event='MiniGameCompleted';data={game:d.game,reward,won,coins:won?45:15,xp:won?15:6};break;}
 case'plant':{const d=z.object({plot:z.string(),itemId:z.enum(['sunflower','carrot'])}).parse(p);if(s.garden[d.plot])throw Error('Plot is occupied');if(!s.inventory[d.itemId])throw Error('Buy seeds first');event='SeedPlanted';data={...d,readyAt:Date.now()+60000};break;}
 case'harvest':{const d=z.object({plot:z.string()}).parse(p);const plot=s.garden[d.plot];if(!plot||plot.readyAt>Date.now())throw Error('Still growing');event='PlantHarvested';data={plot:d.plot,coins:100,xp:20};break;}
 case'adopt':{const d=z.object({name:z.string().min(2).max(16),kind:z.string()}).parse(p);if(s.petling)throw Error('You already have a petling');if(s.coins<350)throw Error('Not enough coins');event='PetlingAdopted';data={...d,price:350};break;}
 default:throw Error('Unknown command');}
 return NextResponse.json(append(id,event,data));}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Command failed'},{status:400});}}
